/**
 * Uploaded raster images have a 400px WebP derivative generated by the API.
 * Card-sized placements should request that derivative directly because the
 * production deployment intentionally bypasses Next's image optimizer.
 */
export function toThumbnailUrl(url: string): string {
  return url.startsWith('/uploads/webp/')
    ? url.replace('/uploads/webp/', '/uploads/thumbnails/')
    : url;
}
